### ISSUE TITLE
Libevent does not like file streams on linux

### ISSUE THREAD

**Issue by igorw** [reactphp/react#104]
You cannot poll file streams with epoll. Libevent does not handle this gracefully and throws awful errors in your face.

We should detect the epoll backend in the libevent event loop and instead of adding file streams to the event loop, add them to a separate array and consider it always ready.

We might be able to find out if a stream is a file stream by using `stream_get_meta_data`. I really hope a PHP stream cannot change from memory to file dynamically. If that is the case, we're kind of screwed with libevent.

**Comment by clue** [comment]
See https://github.com/reactphp/stream/issues/34
