### ISSUE TITLE
Check the $except arg in stream_select

### ISSUE THREAD

**Issue by igorw** [reactphp/react#113]
It allows to detect TCP network errors and the likes. A slightly more accurate description can be found [here](http://stackoverflow.com/questions/589928/socket-programming-how-do-i-handle-out-of-band-data/591104#591104).

Thanks to @DaveRandom.

**Comment by clue** [comment]
Closing this due to a lack of feedback, as we can not reproduce any issues here. If anybody happens to to be able to reproduce this, please come back with more details and we can reopen this :+1:
