### ISSUE TITLE
Can add ev support ?

### ISSUE THREAD

**Issue by shenzhe** [reactphp/react#127]
about ev : http://pecl.php.net/package/ev

**Comment by SerafimArts** [comment]
Now libev has a new API: 
http://php.net/manual/en/book.ev.php
https://bitbucket.org/osmanov/pecl-ev/src/2e65ea35607f?at=master

What about upgrade libev support? Its only one extension who supports php7.

**Comment by clue** [comment]
See https://github.com/reactphp/event-loop/pull/12 and https://github.com/reactphp/event-loop/pull/25 :+1:
