### ISSUE TITLE
Investigate adopting Ardent streams as a replacement for react/stream

### ISSUE THREAD

**Issue by igorw** [reactphp/react#146]
[Ardent](https://github.com/morrisonlevi/Ardent) aims to provide good OO APIs and data structures for PHP. Kind of like a better SPL.

@rdlowrey has been working on a better API [for streams](https://github.com/morrisonlevi/Ardent/compare/streams).

Most of the concepts map to things we have in react. `Streamable` is roughly the equivalent of a `ReadableStream` and `Sink` is roughly the same as a `WritableStream`. Some things are still missing though, for example backpressure (pause/resume, drain event for buffers/sinks).

We should investigate if this could be used over the current eventemitter based API. It seems cleaner and less coupled to specific implementations.

**Comment by clue** [comment]
I'm closing this for now as it hasn't received any input in a while and I believe this to be obsolete. Nowadays, ReactPHP makes extensive use of its Stream interfaces throughout its components and the whole ecosystem and I don't see any plans to change anything about this anytime soon. Changing this would involve a major effort (huge BC break) with unclear gain. Please come back with more details if this is still an issue and we can reopen this :+1:
