### ISSUE TITLE
Track performance

### ISSUE THREAD

**Issue by igorw** [reactphp/react#164]
Since we have some basic performance tests we should start tracking performance between versions and possibly commit a results file per version into version control. There should then be a script to compare the versions.

**Comment by clue** [comment]
I'm closing this for now as it hasn't received any input in a while and I believe this has been resolved in the meantime. Many of our component now come with benchmarking examples that are also run in Travis CI which allows us to keep track of how performance evolved over time (hint: performance is awesome :tada:).

Please come back with more details if this problem persists and we can reopen this :+1:
