### ISSUE TITLE
Keyboard interrupt signal problem

### ISSUE THREAD

**Issue by unusorin** [reactphp/react#221]
1. Start a react server.
2. Ctrl + C (Keyboard interrupt signal)

    PHP Warning:  stream_select(): unable to select [4]: Interrupted system call (max_fd=4) in vendor/react/react/src/React/EventLoop/StreamSelectLoop.php on line 141

PHP:

    PHP 5.5.1-2+debphp.org~precise+2 (cli) (built: Aug  6 2013 10:49:43) 
    Copyright (c) 1997-2013 The PHP Group
    Zend Engine v2.5.0, Copyright (c) 1998-2013 Zend Technologies
    with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans

Note:

* I'm using custom signal handler to close the server ( `$loop->stop()` )

**Comment by clue** [comment]
I believe this has been fixed via https://github.com/reactphp/event-loop/pull/44 in the meantime :+1: 

I'm closing this for now, please feel free to come back and open a new issue in the relevant component if this problem persists :+1:
