### ISSUE TITLE
HTTP parser extension

### ISSUE THREAD

**Issue by dhotson** [reactphp/react#233]
Hey guys,

Not sure if you'd be interested, but I wrote a small php extension for the mongrel http parser a while back:
https://github.com/dhotson/httpparser-php

.. it might make for a good optional extension. I agree that having a pure PHP default makes a lot of sense however.

I'd be curious to see if it gives much of a boost over the [simple implementation](https://github.com/reactphp/react/blob/master/src/React/Http/RequestHeaderParser.php) you've included. :-)

**Comment by clue** [comment]
Thanks for sharing your project and letting us know :+1: 

In case anybody feels like implementing this in React, consider looking at #6 first.
