### ISSUE TITLE
Simple Method to GZIP Response

### ISSUE THREAD

**Issue by Blackshawk** [reactphp/react#25]
Right now there doesn't seem to be a simple way to automatically gzip responses and attach the appropriate content-encoding header. Right now you have to do something like this:

``` php
$app->get('/', function(React\Http\Request $request, React\Http\Response $response) use (&$i) {

    $text = gzencode("A generic response with gzip.\n");

    $headers = array('Content-Encoding' => 'gzip',
                     'Content-Type' => 'text/plain', 
                     'Content-Length' => strlen($text));

    $response->writeHead(200, $headers);
    $response->end($text);
});
```

Which works but this gets tedious and I believe its a common enough (and expected) feature that even forcing people to implement an abstraction themselves isn't the best path.

**Comment by clue** [comment]
See https://github.com/reactphp/http/issues/48 :+1:
