### ISSUE TITLE
Eventloop using generators

### ISSUE THREAD

**Issue by Imunhatep** [reactphp/react#299]
I've created <a href="https://github.com/Imunhatep/rephp/blob/master/src/Rephp/LoopEvent/SchedulerLoop.php">eventloop</a> based on co-routines, made with php generators. The main idea is described by nikic <a href="http://nikic.github.io/2012/12/22/Cooperative-multitasking-using-coroutines-in-PHP.html">in his topic</a>. Currently it's developed on top of React as separate tool, but it could be integrated as another eventloop..

**Comment by clue** [comment]
Thanks for sharing your project and letting us know :+1: 

If you want more people to notice you project, consider adding it to https://github.com/reactphp/react/wiki/Users or join our IRC channel :+1:
