### ISSUE TITLE
[Http] Implement full HTTP/1.1 spec

### ISSUE THREAD

**Issue by igorw** [reactphp/react#3]
Some todos:
- delimit requests by empty body, content-length or chunked encoding ([as defined by the RFC](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4))
- keepalive
- 100-continue handling (could be improved by adding a separate event for that header)
- pipelining
- multipart parsing ([inspiration](https://github.com/hinathan/edges-php/blob/master/lib/Event/HTTP/MultipartParser.php))

We also need to decide how to handle encoding of outgoing data. There are different use cases for modifying the response, some of which may require buffering: websockets, gzip compression, chunked encoding.

**Comment by andig** [comment]
Is there any progress? I understand without this solved there is no simple reading POST requests?

**Comment by onigoetz** [comment]
I started work on reactphp/http#13 and that adds the ability to read POST request parameters

But don't know how to finalize the part with file uploads. we should implement each upload a a stream, but I don't know how to do it.

If you want to give a hand, you're welcome to do so.

**Comment by andig** [comment]
Imho simple post handling is a very necessary first step. Why not skip multipart for now?

**Comment by onigoetz** [comment]
Actually, POST is also sent through multipart. An implementation of POST without multipart would be incomplete.

**Comment by clue** [comment]
See https://github.com/reactphp/http/issues/39 and https://github.com/reactphp/http/issues/96
