### ISSUE TITLE
HHVM hacklang `async` and `await` keywords on the roadmap

### ISSUE THREAD

**Issue by RdeWilde** [reactphp/react#305]
Now that HHVM is released with support for HACK-lang, it is possible to use new features like 'async' (http://docs.hhvm.com/manual/en/hack.async.php). What will be the impact on React?

Will React make use of these features? As I'm not very familiair with React yet, what would be important differences between React promises and Hack asyncs?

**Comment by no1youknowz** [comment]
@JordanRL That sounds awesome, do let us know when you do OS the framework.

**Comment by cboden** [comment]
@no1youknowz Facebook seems to be putting a lot more into async now. I'll be revisiting it once they have streams supporting the async syntax.

**Comment by no1youknowz** [comment]
yay, 3.6 is finally out :+1:

**Comment by joshdifabio** [comment]
http://docs.hhvm.com/manual/en/function.hack.stream-await.php

**Comment by aftabnaveed** [comment]
is ReactPHP supported on HHVM ?

**Comment by clue** [comment]
> is ReactPHP supported on HHVM ?

Yes, ReactPHP does support running on HHVM.

(Though this issue is more geared towards taking advantage of HHVM hacklang's `async` and `await` keywords)

**Comment by clue** [comment]
I'd like to make this actionable, so I'm wondering what needs to be done here? :+1: 

React runs on both Zend PHP and HHVM and it's unlikely this is going to change any time soon.

The `async` and `await` keywords are currently only supported on HHVM and we currently do not take advantage of them.

How could we possibly take advantage of them? What kind of benefits would this give us?

**Comment by clue** [comment]
I'm closing this for now as it hasn't received any input in a while and I believe this has been answered. Please come back with more details if this problem persists and we can reopen this :+1:
