### ISSUE TITLE
Reverse HTTP support (PTTH)

### ISSUE THREAD

**Issue by adamelso** [reactphp/react#314]
I'm creating an [AirPlay client][1] for Apple TV in PHP.

I've managed to get as far POSTing a video stream to the Apple TV.

```php
$in = "POST /play HTTP/1.1\r\n";
$in .= "Host: Apple-TV.local\r\n";
$in .= $httpHeaderStrings . "\r\n\r\n";
$in .= $videoXmlPlistBody;

$addr = gethostbyname('Apple-TV.local');
$client = stream_socket_client("tcp://$addr:7000", $errno, $errorMessage);

fwrite($client, $in);
$response = stream_get_contents($client);

fclose($client);

```

Problem with this is that the Apple TV will close the connection after about 60 seconds or so during video playback. This is because the Apple TV then makes a reverse HTTP request back to me, and closes the connection when it cannot get a response.

Assuming that I was able to replicate the initial request in React, I'm still wondering how to go about implementing a listener for the reverse requests, if it is possible in React. I tried running a server as a child process based on of the examples but I have little idea.

Related links:
http://tools.ietf.org/id/draft-lentczner-rhttp-00.txt
http://wiki.secondlife.com/wiki/Reverse_HTTP
http://reversehttp.net/relay-http-spec.html
http://nto.github.io/AirPlay.html#video-httprequests

### Example reverse HTTP requests ###
Apple TV -> My Computer (Request)
```
POST /reverse
Upgrade: PTTH/1.0
Connection: Upgrade
X-Apple-Purpose: event
Content-Length: 0
User-Agent: MediaControl/1.0
X-Apple-Session-ID: 1bd6ceeb-fffd-456c-a09c-996053a7a08c
```

My Computer -> Apple TV (Response)
```
HTTP/1.1 101 Switching Protocols
Date: Thu, 23 Feb 2012 17:33:41 GMT
Upgrade: PTTH/1.0
Connection: Upgrade
```

Cheers!

[1]: https://github.com/archfizz/phpairplay

**Comment by cboden** [comment]
Hi @adamelso. Sorry for the painfully slow response. 

This is something React could; you'd have to do a bit of the PTTH protocol work though. I don't think our HTTP server is quite flexible enough to handle the reverse at the moment. You could tackle this in a couple different ways: Implement PTTH on top of React/Socket or make some changes to React\Http to manage upgrade headers.

**Comment by frodeborli** [comment]
The protocol seems to be identical. What you need to do is to do is as far as I can see:

1. Send the appropriate `HTTP/1.1 101 Switching Protocols` response according to whatever PTTH requires.
2. Keep reading data from the $request object and write data to the $response object.

You would have to do this in a non-blocking way, of course.

WebSockets are very similar to what PTTH is doing, so you could look at this project:

https://github.com/maxnachlinger/reactjs-websocket-example

**Comment by clue** [comment]
Thanks for the discussion so far, I think this has already mentioned some very good pointers! :+1: 

I agree that PTTH can probably be implemented either on top of or perhaps even within our http component.

I believe this has been answered and I'm closing this for now, please feel free to come back to this ticket with more details if this problem persists and we can reopen this :+1:

**Comment by adamelso** [comment]
@clue Sure thing, I've been following the advice given which has been very good and although I've still yet to make it work, I think I'm close to a solution (providing I can find time:)). And if it works really well I'll share it here 👍
