### ISSUE TITLE
Memory leak with real http requests under PHP-CGI

### ISSUE THREAD

**Issue by nazar-pc** [reactphp/react#320]
PHP-CGI 5.5 (Ubuntu x64).
While running `test-memory-http.php` memory consumption is growing with real requests (memory of php-cgi process, internally it logs 768 KiB and doesn't change).

Also, there is no such problem with PHP-CLI, which is weird I think.

Freshly installed versions of everything.

**Comment by clue** [comment]
React is designed to run from the CLI, so I'm not sure how this is relevant? :)

Does this problem persists, is this still an issue to you?

**Comment by nazar-pc** [comment]
I have PHP 7.0.8 right now and both CLI and CGI work exactly the same and without memory leaks.
