### ISSUE TITLE
A mailing list or subreddit for React

### ISSUE THREAD

**Issue by F21** [reactphp/react#325]
This is not an issue, but I am not sure where it should be posted.

Anyway, I think it would be very useful if there is a mailing list or subreddit for React. It would make it much easier for the community to discuss react topics which are not bug reports/issues.

**Comment by cboden** [comment]
While it's not official, try hitting up http://stackoverflow.com/tags/reactphp. We also have an IRC channel on freenode (reactphp). 

My concern with an official mailing list or subreddit is curation. I wouldn't want to officially support a help forum if we couldn't ensure everyone is helped. I can't speak on anyone else's behalf but I know that I personally couldn't guarantee the time to do so.

**Comment by F21** [comment]
All good points. Although for a subreddit, I wouldn't really consider it to be an avenue for support, but more of a place for general discussion and happenings in the reactphp community.

I didn't know you guys have an IRC channel. It should be mentioned on the website! :smile:

**Comment by clue** [comment]
> My concern with an official mailing list or subreddit is curation. I wouldn't want to officially support a help forum if we couldn't ensure everyone is helped. I can't speak on anyone else's behalf but I know that I personally couldn't guarantee the time to do so. 

I think this is a very compelling reason and I'm having to agree :+1:  

Let's make this actionable, what is the motivation for this ticket, how can this be resolved?

**Comment by clue** [comment]
I'm closing this for now as it hasn't received any input in a while and I believe this has been answered. Please come back with more details if this problem persists and we can reopen this :+1:
