### ISSUE TITLE
Failed to download guzzle/parser -> Please update composer.lock

### ISSUE THREAD

**Issue by sdnet-mp** [reactphp/react#329]
Composer update / init brings the following error

  - Installing guzzle/parser (v3.9.2)
    Downloading: Connecting...    Failed to download guzzle/parser from dist: The "https://api.github.com/repos/guzzle/parser/zipball/6874d171318a8e93eb6d224cf85e4678490b625c" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing guzzle/parser (v3.9.2)
    Cloning 6874d171318a8e93eb6d224cf85e4678490b625c

You may want to update composer.lock
with

https://api.github.com/repos/guzzle3/parser/zipball/6874d171318a8e93eb6d224cf85e4678490b625c

**Comment by WyriHaximus** [comment]
Is by any chance your composer.lock rather old and includes the download paths from before the repo move? (The composer.lock includes the exact download location of the package's version.)

**Comment by cboden** [comment]
Can you provide more details of how you got this message to come about? I just ran this and it installed everything properly (including guzzle/parser):

    composer require react/react

**Comment by sdnet-mp** [comment]
yes, I can provide more information for this.

- I have downloaded reactphp from https://github.com/reactphp/react into a
new folder
- I used composer.bat as explaind at https://getcomposer.org/doc/00-intro.md
C:\Xampp\php\php -r "readfile('https://getcomposer.org/installer');" | php
C:\Xampp\php\echo @php "%~dp0composer.phar" %*>composer.bat

- Then I used composer.bat to generate the vendor folder in the reactphp
project.
later i got the error that the file was not found.
Check link:
https://api.github.com/repos/Guzzle/parser/zipball/6874d171318a8e93eb6d224cf85e4678490b625c

{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}

So I changed the link in composer.lock to
https://api.github.com/repos/Guzzle3/parser/zipball/6874d171318a8e93eb6d224cf85e4678490b625c

and everything was just fine

composer.lock
...
{
            "name": "guzzle/parser",
            "version": "v3.9.2",
            "target-dir": "Guzzle/Parser",
            "source": {
                "type": "git",
                "url": "https://github.com/Guzzle3/parser.git",
                "reference": "6874d171318a8e93eb6d224cf85e4678490b625c"
            },
            "dist": {
                "type": "zip",
                "url": "
https://api.github.com/repos/Guzzle3/parser/zipball/6874d171318a8e93eb6d224cf85e4678490b625c
",
                "reference": "6874d171318a8e93eb6d224cf85e4678490b625c",
                "shasum": ""
            },
            "require": {
                "php": ">=5.3.2"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "3.7-dev"
                }
            },
            "autoload": {
                "psr-0": {
                    "Guzzle\\Parser": ""
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "description": "Interchangeable parsers used by Guzzle",
            "homepage": "http://guzzlephp.org/",
            "keywords": [
                "URI Template",
                "cookie",
                "http",
                "message",
                "url"
            ],
            "time": "2014-02-05 18:29:46"
        },



2015-05-15 16:39 GMT+02:00 Chris Boden <notifications@github.com>:

**Comment by clue** [comment]
I've just checked this, the http and http-client components are well tested and we can not reproduce this?

I'm closing this for now, as this hasn't received any input in a while and I believe this might have been fixed in the meantime. Please come back with more details if this problem persists and we can reopen this :+1:
