### ISSUE TITLE
Running PHP code asynchronously

### ISSUE THREAD

**Issue by chippyash** [reactphp/react#332]
I have been struggling with how to run blocks of php code asynchronously.  I suspect you can't as React currently stands, but thought it worth asking anyway.

Say I have a number of functions, all returning some value, all of which may take some time to run, but don't involve http requests, streams etc,all of which are amply covered by React currently:

I'm trying to construct a Scala type `For Comprehension`. This I can do for synchronous  code blocks, and you can see that in my [working repo](https://github.com/chippyash/working/blob/master/src/chippyash/Funclang/CoffeeShop.php) synchronous() method.

I'm trying to get a pattern to work with that will allow me to do the same but calling each of the constituent parts asynchronously (async() method in same file.) Once I have that, I can then amend the FFor class to compute this on the fly, probably using some kind of React event loop to see whether the next step in the FFor construct can be accommodated now.

I think I am either missing something, or it can't be done, 'cus running the code in async() method still runs synchronously, i.e. step by step.  This is probably because futureTick and tick (which if I use produces no output whatsoever,) are stored in an SplQueue, which by it's nature will do things one at a time.

Can anyone suggest anything?

So, sorry about long winded nature, but as with most technical stuff, it's sometimes the only way!  But I hope you can see the merit of what I am trying to acheive.

**Comment by geggleto** [comment]
You can, http://php.net/pthreads, you just need to thread your php app :)

**Comment by WyriHaximus** [comment]
Another option is to run CPU intensive tasks in a [child process](https://github.com/reactphp/child-process)

**Comment by geggleto** [comment]
http://nikic.github.io/2012/12/22/Cooperative-multitasking-using-coroutines-in-PHP.html

Just came across this gem as well.

**Comment by clue** [comment]
Thanks for the discussion so far, I think this has already mentioned some very good pointers! :+1: 

I'm closing this for now as it hasn't received any input in a while and I believe this has been answered. Please come back with more details if this problem persists and we can reopen this :+1:
