### ISSUE TITLE
 Wrong types in PHPDoc

### ISSUE THREAD

**Issue by Arekusei** [reactphp/react#333]
```php
    /**
     * ...
     * @param numeric  $interval The number of seconds to wait before execution.
     * @param callable $callback The callback to invoke.
     *
     * @return TimerInterface
     */
    public function addTimer($interval, callable $callback);
```
`numeric` type does not exist in php and phpdoc.
More correctly `int|float` or just `float`. http://phpdoc.org/docs/latest/guides/types.html
Now this is some difficulty with code analyzers.

PS Sorry for bad English.

**Comment by clue** [comment]
Thanks for spotting! I suppose this is related to the event-loop component? Can you please file this in the relevant component(s)? Thanks!

**Comment by Arekusei** [comment]
It's code from https://github.com/reactphp/event-loop/blob/master/src/LoopInterface.php
But maybe in other parts reactphp be the same artifacts.
I'm a little did not understand you. You want that I moved this issue?

**Comment by Arekusei** [comment]
Sorry. Just I noticed that round to fix it. But in the release of a fix yet.
The release of version 0.4.1 was a year ago. When will the next update?

**Comment by clue** [comment]
I've just looked up the latest release and I believe this has been fixed in the meantime :+1: 

I'm closing this for now, please feel free to come back with more details if this problem persists and we can reopen this :+1:
