### ISSUE TITLE
SMTP Server

### ISSUE THREAD

**Issue by SamMousa** [reactphp/react#334]
I have implemented an SMTP server using react.
Not sure if anyone is interested, or if the reactphp team might want to adopt it.
It uses PSR-7 MessageInterface to wrap an email with headers and body.

My plan is to implement an SMTP client as well.

https://github.com/SAM-IT/react-smtp

**Comment by clue** [comment]
> Not sure if anyone is interested, or if the reactphp team might want to adopt it.

Nice to see :) I'm sure this is relevant to some people!

React provides the necessary core, low-level components to build these higher-level abstractions and a vivid ecosystem to help these grow.

Make sure to add your implementation to the list of known third-party components in the wiki: https://github.com/reactphp/react/wiki/Users

Other than that, welcome on board :)

**Comment by WyriHaximus** [comment]
Looks good, while I personally don't have a use for it, it's good to see someone building an SMTP project :+1:

**Comment by vicary** [comment]
Can this be added to reactphp.org?

**Comment by SamMousa** [comment]
@vicary, I'm fine with that =)

**Comment by clue** [comment]
This has been added to the wiki, so I feel this ticket can be closed :+1: 

> Can this be added to reactphp.org?

Questions regarding the main homepage are best directed to its repo here: https://github.com/reactphp/website
