### ISSUE TITLE
Is it possible to start a React loop and continue executing other code?

### ISSUE THREAD

**Issue by elnur** [reactphp/react#339]
I need this for tests that do real HTTP requests to the app. Basically, I want to start a React loop in `setUp()` and execute tests after that. I need tests and the app to share the same DI container and hence I need them both executing in the same process.

Is this even possible?

**Comment by frodeborli** [comment]
Potentially you could create a "tick" function: http://php.net/manual/en/function.register-tick-function.php


<http://php.net/manual/en/function.register-tick-function.php>This function will of course block the react loop while it's executing. You can also look into the Threading capabilities of PHP: http://am1.php.net/manual/en/class.thread.php



________________________________
Fra: Elnur Abdurrakhimov <notifications@github.com>
Sendt: 19. oktober 2015 17:21
Til: reactphp/react
Emne: [react] Is it possible to start a React loop and continue executing other code? (#339)


I need this for tests that do real HTTP requests to the app. Basically, I want to start a React loop in setUp() and execute tests after that. I need tests and the app to share the same DI container and hence I need them both executing in the same process.

Is this even possible?

-

**Comment by jmalloc** [comment]
Does the app run on the React event loop?  If not you'll be hard pressed to get them running side-by-side unless you can somehow get your app to call `LoopInterface::tick()` periodically.

Perhaps registering a PHP tick function as @frodeborli suggests would work, but PHP tick functions will only be executed every <N> instructions, so if your app is blocking waiting on a connection from the tests you might end up with a "deadlock" scenario, for lack of a better word.

Is there any particular reason you need the same DI container *instance* (and not just the same DI configuration)?

**Comment by elnur** [comment]
> Is there any particular reason you need the same DI container instance (and not just the same DI configuration)?

I need to assert some state of the container after a HTTP request has been served by the app.

> Does the app run on the React event loop?

I'm not sure I understand your question.

Basically, an instance of the container is created for tests themselves. And then another instance is running for the app itself, served by PHP-FPM via nginx. All I want to do is add HTTP serving capabilities to the container used by tests, so that I could make requests to it instead to the actualy instance of the app.

I don't think I understand all this tick stuff. I understand threads though, and maybe they're the solution for this problem. But I have to reconfigure/recompile PHP with ZTS support, etc. I don't want to go there if there's a simpler solution to the problem.

Maybe I'm tackling this problem from the wrong angle. Now that I think of it, it doesn't make much sense to start a React loop in `setUp()`; it probably makes more sense to start a loop in the container itself. Does this make any sense? If it means anything, I'm using the Symfony framework. Can I add HTTP serving capabilities to it somehow?

**Comment by frodeborli** [comment]
I am pretty sure you can have two servers on the same event loop, they just have to listen on two different ports.

**Comment by elnur** [comment]
I don't need two servers. I just want to add HTTP capabilities to the container.

**Comment by elnur** [comment]
Do I understand it correctly that `$loop->run()` is **always** blocking meaning code execution stops at that method and doesn't go further?

**Comment by elnur** [comment]
Looks like tick functions are not the solution because they're blocking too. Seems like the only way to do this is threading.

**Comment by marcj** [comment]
The whole reactphp architecture is based on a loop. You can either start that loop or you can trigger each tick yourself. Means, if you need to setup a event-loop with its http-server etc and then setup your test-suite, then you need to call each `tick($timeout = 0)` (tick means "handle everything that is in the buffer currently, which would be automatically be done if you call `run()` as this is nothing more than calling `tick()` in a while-loop) and then do your assertion after that.

**Comment by elnur** [comment]
@marcj, sounds promising. Does it mean that I do [this example][1] but instead of doing `$loop->run()` I do `$loop->tick()` when I need it? Or is it more complex than that?

[1]: https://github.com/reactphp/react#usage

**Comment by elnur** [comment]
Finally, I've solved this problem with `register_tick_function([$this->loop, 'tick']);`.

Thank you all guys for input. Each of you added a piece to complete the puzzle. :+1: 

The next problem to solve is SSL support...

**Comment by elnur** [comment]
Never mind. The problem I run into now is that there are no statements being executed after I launch a browser via Selenium and do an HTTP request to the app. In other words, the browser sits there waiting for its request to get handled, and PHP sits there waiting for Selenium, and React sits there waiting for a tick. Epic fail. :laughing: 

Any other ideas on this?

**Comment by dustingraham** [comment]
What I think you're looking for is to create a loop at setup.

Then `$loop->run()` in the test. Kick off Selenium. Then tou need to add a [timeout timer](https://github.com/reactphp/promise-timer) to kill the loop after a certain time.

Then depending on how you have your test configured, the test itself may be able to kill the loop upon success, and if the loop hits the timeout, fail the test.

But, yes, starting the loop is blocking. You can't get around that, that's how it works.

**Comment by clue** [comment]
Thanks for the discussion so far, I think @dustingraham has got it all right, the key here is to start the loop within your test :+1: 

I believe this has been answered and I'm closing this for now, please feel free to come back to this ticket with more details if this problem persists and we can reopen this :+1:
