### ISSUE TITLE
which loop extension to install ?

### ISSUE THREAD

**Issue by flip111** [reactphp/react#340]
i saw this in the factory code

```php
        if (function_exists('event_base_new')) {
            return new LibEventLoop();
        } else if (class_exists('libev\EventLoop')) {
            return new LibEvLoop;
        } else if (class_exists('EventBase')) {
            return new ExtEventLoop;
        }

        return new StreamSelectLoop();
```

Looks like i could enable one of those other loops by installing some extensions. Does some someone which one is best to install? I guess in terms of performance, stability and features?

**Comment by jsor** [comment]
I think the order of the if statements tells you which one is preferred over the other. See also https://github.com/reactphp/react/wiki/Event-Loop-Implementations

**Comment by flip111** [comment]
looking at that benchmark page (from the wiki you linked) libev (native) seems most performant and libevent seems the worst .. so that seems to contradict the order of the if statements. Quite an old benchmark as well actually

**Comment by kugu** [comment]
What about PHP 7? Which libraries are stable?

**Comment by dustingraham** [comment]
@jsor As flip111 mentioned from the article linked at the link you linked.

http://libev.schmorp.de/bench.html _"The benchmark clearly shows that libev has much lower costs and is consequently **faster than libevent**."_

**Comment by clue** [comment]
Thanks for the discussion so far, I think this has already mentioned some very good pointers! :+1: 

This repository does not contain any code related to the event loop anymore, so I think this would be better discussed in the related component: https://github.com/reactphp/event-loop

I'm closing this for now, please feel free to come back and open a new issue if this needs more details :+1:
