### ISSUE TITLE
React stop work since php 5.6.14

### ISSUE THREAD

**Issue by nadavvin** [reactphp/react#341]
example in FrontPage (http://reactphp.org/) and any other usages like socket not working in php 5.6.14, 5.6.15

It work in php 5.613 and php 7

**Comment by clue** [comment]
Does this problem persist?

Can you give some more details on *what* doesn't work?

Afaict we're not aware of any issues that would make this whole project incompatible with any recent PHP version.

**Comment by clue** [comment]
Closing this due to a lack of feedback, as we can not reproduce this. Please come back with more details if this problem persists and we can reopen this :+1:
