### ISSUE TITLE
Problem with certificate verification

### ISSUE THREAD

**Issue by emil-nasso** [reactphp/react#342]
I have a problem with connecting to a TLS-encrypted irc server. To debug this I added a print before this line:

https://github.com/reactphp/socket-client/blob/master/src/StreamEncryption.php#L119

And i get this output: 

>SNI_server_name is deprecated in favor of peer_name
>SNI_server_name is deprecated in favor of peer_name
>stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
>error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

I put together this quick test

```php
<?php
$context = stream_context_create(array(
    'ssl' => array(
        'verify_peer' => true,
        'verify_peer_name' => false
    )
));

stream_socket_client("tls://xx.xx.xx.xx:6697", $errno, $errstr, 10, STREAM_CLIENT_CONNECT, $context);
print $errno;
print $errstr;
```

With `verify_peer = true` i get the same verification error as from react. Setting `verify_peer = false` lets me connect without errors.

Is there any way for me to control this in react?

**Comment by clue** [comment]
Hi @emil-nasso, looks like you're looking for https://github.com/reactphp/socket-client/issues/4.

There's a pending PR at https://github.com/reactphp/socket-client/pull/52 which is still awaiting review. This should allow you to pass the context parameters just as you've documented.
