### ISSUE TITLE
[RFC] Remove branch-alias definitions

### ISSUE THREAD

**Issue by clue** [reactphp/react#343]
Most (but not all) of our components use a [`branch-alias` definition](https://getcomposer.org/doc/articles/aliases.md) for Composer. This ticket aims to serve as a discussion basis whether it actually makes sense to keep these.

IMHO having a `branch-alias` is a real PITA, as it provides very little value and often ends up getting out of sync with the branch.

As an alternative, I would suggest dropping the definitions and using an [inline alias](https://getcomposer.org/doc/articles/aliases.md#require-inline-alias) as required:

``` bash
$ composer require "react/socket-client:dev-master as 0.5.0"
```

**Comment by jsor** [comment]
I always understood branch-alias as requiring a dev-version of an upcoming tag, eg. 0.5.0. If the version 0.5.0 is tagged and the branch-alias is changed to 0.6.0, i still get ~0.5.0 which isn't the case if i'm requiring dev-master. But, i may be wrong... ;)

**Comment by clue** [comment]
> I always understood branch-alias as requiring a dev-version of an upcoming tag, eg. 0.5.0.

This is correct, and I see *some* (but little) use in this.

> If the version 0.5.0 is tagged and the branch-alias is changed to 0.6.0 […]

The `branch-alias` will have to be updated *before* the first change with a BC break lands. Note that this most likely isn't right after a tag has been set, because there may still be more future patch level releases (like 0.5.x). Because we would regularly have to check whether the `branch-alias` is still in line the current line of development, I consider this a real PITA.

My main point here is: Maintaining the `branch-alias` requires continuous effort, but is it really worth it? Is much gained by maintaining this? Should we really *endorse* depending on development versions?

**Comment by jsor** [comment]
I'm undecided on this, could live with either decision. Any thoughts by @WyriHaximus or @cboden?

**Comment by cboden** [comment]
I haven't found it particularly useful when using React in outside projects and it is a PITA to maintain. Unless someone comes up with a compelling argument to keep them I'm +1 for removing them.

**Comment by WyriHaximus** [comment]
Honestly it seems to cause more confusion then it has any benefits at the moment. I'm in favour of removing them :+1:

**Comment by jsor** [comment]
👍

**Comment by clue** [comment]
Thanks for the feedback, I think we all agree :+1: 

Does anybody feel like filing a few very simple PRs? :shipit:

**Comment by WyriHaximus** [comment]
Sure I'll get on it tonight :smile:

**Comment by WyriHaximus** [comment]
Ok that is all of them I think :sunglasses:

**Comment by clue** [comment]
Closed via referenced tickets :+1:
