### ISSUE TITLE
EventSource's response has a MIME type

### ISSUE THREAD

**Issue by syntheticsh** [reactphp/react#347]
I'm testing out react with addition of clue/php-sse-reactt, but can't make it work properly.
I'm using server like in the example: 

```
require __DIR__ . '/../vendor/autoload.php';

use Clue\React\Sse\BufferedChannel;
use React\Http\Request;
use React\Http\Response;


$loop = React\EventLoop\Factory::create();
$socket = new React\Socket\Server($loop);

$channel = new BufferedChannel();

$http = new React\Http\Server($socket);

$http->on('request', function (Request $request, Response $response) use ($channel) {
    echo 'connected' . PHP_EOL;

    $headers = $request->getHeaders();
    $id = isset($headers['Last-Event-ID']) ? $headers['Last-Event-ID'] : null;

    $response->writeHead(200, array('Content-Type' => 'text/event-stream', 'Cache-Control' => 'no-cache'));
    $channel->connect($response, $id);

    $response->on('close', function () use ($response, $channel) {
        echo 'disconnected' . PHP_EOL;
        $channel->disconnect($response);
    });
});

$loop->addPeriodicTimer(2.0, function() use ($channel) {
    $channel->writeMessage('ticking ' . mt_rand(1, 5) . '...');
});

$socket->listen(1337);

echo 'Server now listening on localhost:' . $socket->getPort() . PHP_EOL;
$loop->run();
```

Than I run it with bash: php server.php

When I'm doing script:
`var eventSource = new EventSource('server.php');`

it gives an error:
`EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.`
What might be the problem?

**Comment by clue** [comment]
> it gives an error:
EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.

Hi @syntheticsh, this appears to be a higher level protocol error, looks like everything on the React side of things seems to work just fine.

May I ask you to file this issue in the lib you're using to handle SSE instead, i.e. https://github.com/clue/php-sse-react ?

In the meantime, you may also want to verify your server sends the correct HTTP headers on the command line like this:

```bash
$ echo -e "GET / HTTP/1.0\r\n\r\n" | nc localhost 1337
```

**Comment by syntheticsh** [comment]
I used 
`echo -e "GET / HTTP/1.0\r\n\r\n" | nc localhost 1337`
and it returned 
```
HTTP/1.1 200 OK
X-Powered-By: React/alpha
Content-Type: text/event-stream
Cache-Control: no-cache
Transfer-Encoding: chunked
```

**Comment by clue** [comment]
For the reference: Resolved via https://github.com/clue/php-sse-react/issues/1
