### ISSUE TITLE
PHP Version requirement

### ISSUE THREAD

**Issue by SamMousa** [reactphp/react#350]
Since this package is still in alpha does it make sense to up the PHP version requirement?

http://php.net/supported-versions.php

PHP5.5 no longer has security support.

So I suggest upping the requirement to PHP5.6.

**Comment by WyriHaximus** [comment]
Would really like to see this in 0.x or 1.0 :+1:

**Comment by clue** [comment]
> this package is still in alpha

Most components are stable in the sense of SemVer, only a few are still considered beta.

> PHP5.5 no longer has security support.

This has been discussed at length already, but an important distinction has to be made: PHP 5.5 is no longer officially supported by Zend!

This does *not* mean it no longer receives any support! Many other commercial and free vendors *do* still support older PHP versions and backport security fixes even to versions as old as 5.3. This includes many of the known Linux distributions such as Debian, Ubuntu etc. which is likely where most people get their version of PHP from.

That being said, I *personally* encourage every single user to upgrade to the latest PHP release available ASAP. In particular PHP7 shows significant performance improvements!

Also, given the fact that React *mostly* runs as a CLI program the old argument of shared hosting doesn't really apply here.

If you can, then please upgrade!

> So I suggest upping the requirement to PHP5.6.

What's the motivation for this change?

I'm fine with updating our requirement *IF* we actually require any of the newer futures.

Until then, I'm :-1: on dropping support for older versions just for the sake of it.

Let's *please* not get this political? :+1:

**Comment by WyriHaximus** [comment]
> I'm fine with updating our requirement IF we actually require any of the newer futures.

That would be my main reason to decide if we want an upgrade or not.

**Comment by clue** [comment]
> Personally I don't like having to take into account whether or not I can use features for each project I contribute to, for example '::class'. Even though these features are technically never "needed". 

I understand that this may occasionally require some additional attention, but AFAICT this has never caused any major issues so far. All components are tested against every supported PHP versions, so Travis should catch anything we've missed.

> I think people developing on "cutting edge" stuff like ReactPHP are not very likely to be stuck on 3+ years old PHP versions, but I have no evidence to back that up.

I understand many people see ReactPHP as "cutting edge" :-) And while I understand the reasoning, I can assure you ReactPHP is absolutely production ready and used in some very, very traditional, stable and critical environments.

I'm not saying we need to support legacy versions forever, but I personally know of several thousands of installations on PHP 5.3 and PHP 5.5, mostly due to Ubuntu LTS releases, which are in fact still supported.

> Maybe we could use the thumbs up / down as sort of a vote system?

I feel that this is a *highly political* topic and assume many people will vote for an updated version requirement. As such, I would rather collect some proper pros and cons first before casting a vote :+1:

**Comment by SamMousa** [comment]
@clue 

>  Most components are stable in the sense of SemVer, only a few are still considered beta.

Can you elaborate? From packagist most packages are still at 0.* which is not stable according to semver.

**Comment by clue** [comment]
I agree, I probably should clarify :-)

Some of our components are 1.* or 2.*, which clearly follow SemVer.

The list you've posted is still 0.x.* which according to SemVer means they're unstable. We do consider these versions to be stable in the sense of a x.* version, but expect some breaking changes before they get declared "officially stable".

(Note that I'm not saying this interpretation is a good thing, but that's the way it is :) )

**Comment by SamMousa** [comment]
@clue, why not just tag them as 1.0 then and when you change the public API you up the major version?

The goal of semver is not to limit the number of major updates, if the component is considered stable and is in use as stable it will be easier for everyone to give it a stable version number ;-)

**Comment by clue** [comment]
> @clue, why not just tag them as 1.0 then and when you change the public API you up the major version?

This sounds sane, care to file a separate issue for this as it's unrelated to our dependency on PHP? :+1:

**Comment by SamMousa** [comment]
@clue Sure, in each sub repository I assume?

**Comment by clue** [comment]
Nowadays, this repo here is mostly used for meta discussion, related to all components. I guess it makes sense to keep track of this here to achieve consensus first and then apply this to all affected components.

**Comment by SamMousa** [comment]
Pro: By using the `::class` constant instead of strings we reduce the number of hardcoded strings and allow for better static code analysis.

**Comment by clue** [comment]
Discussion about moving to PHP 7+ now takes place in #374.

I'll assume this is resolved and will close this for now, please feel free to report back otherwise :+1:
