### ISSUE TITLE
[RFC] Separate contracts from implementation

### ISSUE THREAD

**Issue by SamMousa** [reactphp/react#352]
Should, at some point, the interfaces be extracted into several packages?

Ideally I think custom loop implementations should provide some virtual `EventLoop` package that other libraries can then require.

https://getcomposer.org/doc/04-schema.md#provide

Not in any rush, but could be something that improves and eventually simplifies the repositories.

**Comment by clue** [comment]
There's ongoing effort to standardize some of the most needed interfaces, so I think this makes sense :+1: 

The main concern appears to be interoperability with other projects.

Note that while I think this makes sense, this does not necessarily improve or simplify our components: it's likely this will actually involve additional work that could make these more complex.

**Comment by clue** [comment]
Closing this due to a lack of feedback, as I'll assume this is resolved. Please come back with more details if you think this is still relevant and we can reopen this :+1:
