### ISSUE TITLE
PHPUnit Tests

### ISSUE THREAD

**Issue by shaunbramley** [reactphp/react#354]
References: A. Twitter conversation between myself and @WyriHaximus https://twitter.com/shaunbramley/status/765939778277806080
B. reactphp/child-process#5
C. sebastianbergmann/phpunit#2194

As per @WyriHaximus request within Ref A, I am submitting an issue that affects all reactphp test suites.

As per Ref C, unit tests that execute `getMock()` with PHPUnit 5.4+ will receive warning messages for each call indicating that the method has been deprecated, as evidenced at Ref B.

Absence of PHPUnit from `require-dev`, results in the expectation that unit tests will run error free with latest tooling.  Yet, when latest tooling is used, tests throw warnings (unexpected behaviour).  Part of the issue seems to stem from Ref B, which highlights a decision to avoid referencing PHPUnit as a developmental requirement.

**Comment by WyriHaximus** [comment]
Another reason to get phpunit in require-dev is that, maybe combined with a makefile, getting started on testing is easier rather than having to install phpunit seperately. Anther plus side is that you can lock it down to a supported version. I'm all :+1: for this, but interested to hear what @clue, and @jsor think.

**Comment by clue** [comment]
I understand there are *some* downsides to adding a dependency on phpunit to our components, but IMHO they really only boil down to a slightly slower (default) installation, which I consider only a minor inconvenience. On the other hand, adding a dependency will result in a more reliable setup with versions that are actually supported and continue to work in the future. In a few years, figuring out which version was supported some time ago is going to much much harder, so I'd suggest rather locking this now.

As such, my vote goes to adding the dependency :+1:

**Comment by WyriHaximus** [comment]
The good thing is that composer caches this locally. [On Travis there are ways to utilize that for (slightly) faster builds.](https://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/)

**Comment by jsor** [comment]
👍

**Comment by shaunbramley** [comment]
A. [PHPUnit 5.5 Release Notes](https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-5.5.0)
B. [PHPUnit 4.8 Release Notes](https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-4.8.0)
C. reactphp/react#350 

Ref C somewhat relates, as the version of PHPUnit chosen to "lock onto" may impact the minimal version of PHP that libraries support.  Which I have noticed varies between individual libraries.

**Comment by WyriHaximus** [comment]
Think `4.8` makes most sense with our current supported versions. 

@cboden ping; can we move forward or do you have any objections?

**Comment by cboden** [comment]
LGTM

**Comment by WyriHaximus** [comment]
Awesome!

Ping @shaunbramley do you still want to do this? Otherwise I'll do it :smile: .

**Comment by shaunbramley** [comment]
I can certainly start submitting some PR's

**Comment by clue** [comment]
See all linked PRs :shipit: :tada: 

I'll assume this is resolved and will close this for now, please feel free to report back otherwise.
