### ISSUE TITLE
async-interop compatibility

### ISSUE THREAD

**Issue by SamMousa** [reactphp/react#355]
I've opened this ticket in this repo since it does not only apply to the event-loop implementation.

There is a group of developers working on a async-interop spec that allows different vendors to implement event loops and components to work with different event loops.

https://github.com/async-interop/event-loop

While reactphp offers a loop interface that could be implemented by vendors as well, it could be interesting to adopt the "larger" spec.

Is anyone in working on reactphp also part of the async-interop group? If not, what are your thoughts on their spec and would it be good to converge towards a single spec we all obey?

**Comment by WyriHaximus** [comment]
Yup I'm in that interop group. Currently working on an adapter going both ways as a place to start experimenting with it :smile: .

**Comment by SamMousa** [comment]
Ah great to hear that :D, feel free to close or leave open for future discussion! Thanks for the quick reply!

**Comment by WyriHaximus** [comment]
Lets keep it open for now, I'll report back when I have a working prototype, and others can join in the discussion in the mean time

**Comment by WyriHaximus** [comment]
FYI the WIP adapter repo can be found here: https://github.com/WyriHaximus/reactphp-async-interop-loop

**Comment by clue** [comment]
Afaict the async-interop organization looks dead to me and IIRC some of their owners stated that they consider this project failed? I would love to hear back from them either way as this project looks abandoned now.

That being said, Icicle and Amp have now joined efforts under the name Amp and Amp has added adapters for ReactPHP in the meantime, which means that interoperability is not that big of an issue at the moment anyway.

Given that async-interop appears to be dead, I'll close this ticket for now. Please come back with more details if this problem persists and we can reopen this :+1:

I hope this helps!
