### ISSUE TITLE
[FYI] New homepage and logo

### ISSUE THREAD

**Issue by clue** [reactphp/react#356]
FYI only, posting this here only in order to reach a broader audience.

The React project is currently in the process of updating and redesigning its homepage and getting a new logo. If you want to participate, check out the following two issues:

https://github.com/reactphp/website/issues/8
https://github.com/reactphp/website/issues/10

**Comment by jason69** [comment]
Hi!
Thanks for the news, I was wondering if the project was still alive because the last commit is more than 1 year old...
Event driven and async code is the current hype with javascript, and i really love see it coming to PHP...
Please provide a project status...

**Comment by WyriHaximus** [comment]
@jason69 yes it is, however all development is now done on all the components own repositories, you can find those at: https://github.com/reactphp

**Comment by stamster** [comment]
@jason69 Very good comment! Hype with JS is just unbelievable that I begin to wonder how Linux kernel works w/o JS or async-everything stuff. :)
This project is just great, combining PHP's intuitive nature with async event loop, which can be useful for a certain tasks (not for all).

**Comment by clue** [comment]
New logo is now in place via https://github.com/reactphp/branding/pull/3 :tada:
New homepage is now live via https://github.com/reactphp/website/pull/11 :tada: 

See also http://reactphp.org
