### ISSUE TITLE
Question: Can i make rest api with permanent socket connection with reactphp

### ISSUE THREAD

**Issue by demil** [reactphp/react#359]
I need to make REST API, and that api needs to be socket-client and to connect to socket server, and for example we would have endpoints like this:

POST /send

where server would send POST data to socket server, process answer and return response.

Is this posibble with reactphp?

**Comment by clue** [comment]
Absolutely! :) From what I understand your REST API will likely require the http component to receive incoming requests and then use the socket-client component to send outgoing requests.

I hope this helps :+1:

**Comment by demil** [comment]
ini_set('MAX_EXECUTION_TIME', -1);
     set_time_limit(0);
     require_once __DIR__.'/vendor/autoload.php';

     $this->react_start = microtime(true);
     $this->react_count = 0;

     $app = function ($request, $response) {
     $this->react_count++;

     $res = call_user_func($this->react_routes[$request->getPath()]);

     $headers = array('Content-Type' => 'text/plain');
     $response->writeHead(200, $headers);
     $response->end($res);
      };

     $loop = React\EventLoop\Factory::create();
     $socket = new React\Socket\Server($loop);
     $http = new React\Http\Server($socket);

     $http->on('request', $app);

     $socket->listen(3334,'0.0.0.0');
     $loop->run();

Ok, i here have react_routes array which determine which method of main class we call to return response. (this code is method $app->start() )

I cant understand how to make methods:

/socket_connect

to connect with socket

socket_disoconnect

to disconnect with socket

socket_send

to send data to socket.

Do i need two loops? or i can use this one which i used for http server?

**Comment by clue** [comment]
I'm not sure I follow what issue you're facing? Can you break this down into a reproducible gist and possibly provide a diagram of what you're trying to achieve?

> Do i need two loops?

Never, not within a single program at least. Just use DI to pass your single `$loop` instance around.

**Comment by demil** [comment]
There is gist: 

https://gist.github.com/demil/4a81faf65b684a70dc39660d49ee052b

I need to have those 3 functions for connecting, disconnecting and sending data to socket.
this is working http react server, i just dont have idea how to add socket part.

**Comment by clue** [comment]
Your design is still unclear to me. How is your script to supposed to be behave? In particular, what if someone sends a "send" request without first sending a "connect" request? Obviously you want to share some state between these functions, so I'd recommend starting with closures where you can easily bind additional parameters to.

See https://github.com/reactphp/socket-client#async-tcpip-connections for details on how to connect, send messages and then disconnect.

**Comment by demil** [comment]
If someone sends send request and there is no socket connection, response should be - socket connection not active.

**Comment by demil** [comment]
I have created function to start socket, but i don't have any clue how to send to socket or how to disconnect.

Please take look to gist if you have time:

https://gist.github.com/demil/4a81faf65b684a70dc39660d49ee052b

Thank you very much.

**Comment by clue** [comment]
> how to send to socket or how to disconnect.

See the above link or the stream component, you can simply call `$stream->write('message');` to send any kind of data to this stream. Similarly, you can use `$stream->close()` to force-close the connection.

From the code you've just updated it looks like you may want to send outgoing HTTP requests so that your "REST API" works like a proxy? In this case, you're probably better off using the http-client component instead.

Again, it's still a bit unclear what you're trying to achieve. If you need more general programming advice, I suppose this may not be the best platform here. Perhaps consider posting this on stackoverflow or similar?

**Comment by demil** [comment]
You certainly did not understand my requirements from beginings.

I have already using http-client, my REST api should works like a proxy between users and socket connection.

**Comment by demil** [comment]
Problem is lack of documentation for reactphp library.

**Comment by demil** [comment]
I have managed to make everything to work.

I have used react-socket-client and react-http, and i have managed to make REST API gateway to socket.

You were big help to me and i thank you very much.

I just have one question left, which is about react-socket-client.

When i recieve data on $stream->on('data...

is everything that i do with data asynchronous or blocking in compare to next data ariving?

**Comment by clue** [comment]
> I have managed to make everything to work.

Glad you've got this sorted! Feel free to share your findings for others who have trouble getting into this :+1: 

> is everything that i do with data asynchronous or blocking in compare to next data ariving?

All of React's components are completely non-blocking, so you'll only be notified when new data arrives and it's entirely up to you to then handle any data.
