### ISSUE TITLE
reactphp non blocking cron

### ISSUE THREAD

**Issue by demil** [reactphp/react#363]
Is it possible to make non blocking cron jobs with reactphp and how?

If we add multuple periodic timers with some functions to do, will they be independent?

**Comment by clue** [comment]
Absolutely! Just make sure each "function" will be async and not block the loop and there's nothing which prevents you form scheduling your timers to run at specific times :+1: 

I hope this helps! :+1:

**Comment by clue** [comment]
You should make sure your "function" is async and it should not block the loop. If this is not possible, you may want to move it to a separate process (ChildProcess component) or use a queue :+1:
