### ISSUE TITLE
can't find any documentation for reactphp

### ISSUE THREAD

**Issue by pars0097** [reactphp/react#367]
is there any documentation for react?
i couldn't find anything

**Comment by clue** [comment]
Yes, lack of documentation (in particular for this meta repo) is one of the things I'm currently looking into :+1: 

I'd love to get some input on this, so is there anything you're missing in particular?

If you're new to ReactPHP, I'd suggest taking a look at the examples of one of the components (e.g. https://github.com/reactphp/http) or the use cases from our wiki https://github.com/reactphp/react/wiki/Users.

I hope this helps :+1:
