### ISSUE TITLE
Non-availability outside docker container

### ISSUE THREAD

**Issue by gossoudarev** [reactphp/react#368]
Unlike nodejs process, PHP React HTTP listens to something that doesn't allow localhost to be seen outside the container. 
What to do? See netstat comparison of ReactPHP and Nodejs

![node-php](https://cloud.githubusercontent.com/assets/1646403/23487232/c2948dca-fef5-11e6-9b12-23086678f273.png)

**Comment by clue** [comment]
This is actually a Socket feature and it works as expected and documented :-)

If you want to listen on all or some public interfaces, you have to specify which address your server socket is listening on like this:

```php
$server = new Server('[::]:80', $loop);
```

See https://github.com/reactphp/socket#server for more details.

I hope this helps :+1:
