### ISSUE TITLE
How to put reacphp in nginx upstream 

### ISSUE THREAD

**Issue by demil** [reactphp/react#370]
Is it possible to put reactphp process listening on some port in nginx upstream which is userd by fastcgi_pass

for example:

upstream
{
server localhost:5000 (reactphp)
server localhost:9000 (php-fpm)
}

so if react is avilaible it will use reactphp process, and if is not it will pass to php-fpm.
Also how to read fastcgi parameters in reactphp process?

**Comment by shuchkin** [comment]
https://github.com/garveen/fastcgi-react

**Comment by clue** [comment]
I believe this has been answered and I'm closing this for now, please feel free to come back to this ticket with more details if this problem persists and we can reopen this :+1:
