### ISSUE TITLE
Run a function in a child process

### ISSUE THREAD

**Issue by J7mbo** [reactphp/react#371]
Is there a way I can run a function, or callable, in a child process, instead of just a command for an external script? I already have the code I want to execute available at runtime.

**Comment by WyriHaximus** [comment]
Well with react/child-process you can't do that directly. However I've created a package that lets you supply a class to do somewhat the same: https://github.com/WyriHaximus/reactphp-child-process-messenger#hassle-less-example

**Comment by clue** [comment]
I believe this has been answered and I'm closing this for now, please feel free to come back to this ticket with more details if this problem persists and we can reopen this :+1:
