### ISSUE TITLE
A different order for the wiki users page 

### ISSUE THREAD

**Issue by WyriHaximus** [reactphp/react#372]
The users page is slowly growing into a long list you have to search through to find something. I get the chronological appeal but that was doesn't work anymore at this scale. So I am proposing to split the list up in alphabetically sorted categories. I'm also creating a PR on the website linking to the users wiki page.

**Comment by WyriHaximus** [comment]
Ping @reactphp/core

**Comment by clue** [comment]
I agree that this list is *not exactly ideal* and have toyed with the idea myself :+1: Question remains, what exact alternative do you propose? Can these be sorted into distinct "categories" and if so, which categories?

It looks like you have something specific in mind, so I'd say go for it :+1:

**Comment by WyriHaximus** [comment]
Not sure about categories yet, but wanted to let you know before starting 😄

**Comment by WyriHaximus** [comment]
Categories and sorted the page: https://github.com/reactphp/react/wiki/Users

**Comment by WyriHaximus** [comment]
Closing as this has been implemented
