### ISSUE TITLE
[RFC] Move non-core related repositories to a friends of org

### ISSUE THREAD

**Issue by WyriHaximus** [reactphp/react#380]
Several PR's have been to improve non-core related repositories like [`espresso`](https://github.com/reactphp/espresso/pull/13), [`stomp`](https://github.com/reactphp/stomp/pull/44), and [`partial`](https://github.com/reactphp/partial/pull/14) that would be a shame to waste.

I would like to propose moving them over to an friends of org as a home for projects like that and other projects related to reactphp but that don't fit into the core. That way we can keep the focus of the reactphp org on low level infrastructure packages.

Ping @cboden @jsor @clue @msfidelis @the-eater @shadowhand

**Comment by msfidelis** [comment]
I agree with that.

**Comment by shadowhand** [comment]
Good idea.

**Comment by the-eater** [comment]
Sounds good to me :)

**Comment by clue** [comment]
Makes perfect sense to me! These repos are clearly distinct from what others see as the "core" and I agree that this would help making this more obvious. Also, the "core" usually tries to stay neutral on framework choices and alike to foster a diverse ecosystem, while the "friends of org" could certainly use a more opinionated approach :+1:

**Comment by redunta** [comment]
<off-topic>What jargon do you speak gentlemen... friends of org. huh. </off-topic>

**Comment by jsor** [comment]
@redunta The *Friends of `[Project]`* projects are often github organisations which provide libraries related to that project. A popular example is [Friends of Symfony](https://github.com/FriendsOfSymfony). @WyriHaximus created a similar [Friends of ReactPHP](https://github.com/friends-of-reactphp) organistaion.

**Comment by WyriHaximus** [comment]
Closing the issue in favour of follow up issue at #382
