### ISSUE TITLE
Loosen dependency versions?

### ISSUE THREAD

**Issue by siwinski** [reactphp/react#381]
Since this is basically just a meta-package, any chance the dependency versions `0.4.*` could be loosened to `^0.4` in `composer.json`?

**Comment by WyriHaximus** [comment]
During DPC @clue discussed this and in the long run we rather deprecate and abandon this package in the long run as we prefer user to target individual packages directly. Also `0.4.*` is effectively the same as `^0.4` :wink: .

**Comment by siwinski** [comment]
@WyriHaximus  Ok, that makes sense.  Thanks.  I will discontinue use of this meta-package.

Btw,
`0.4.*` matches versions `>= 0.4.0` and `< 0.5.0`
`^0.4` matches versions `>= 0.4.0` and `< 1.0`

**Comment by jsor** [comment]
@siwinski No, as @WyriHaximus said, `^0.4` matches versions `>= 0.4.0` and `< 0.5.0`. See https://getcomposer.org/doc/articles/versions.md#caret-version-range-

**Comment by siwinski** [comment]
@jsor @WyriHaximus Oh, wow. I'm so sorry.  I have been treating that case wrong all this time :(  I apologize.

**Comment by jsor** [comment]
No need to be sorry, took me some time too until i learned that pre-1.0 versions are treated differently with `^`. :)
