### ISSUE TITLE
[RFC] Moving strategy for espresso, stomp, and partial

### ISSUE THREAD

**Issue by WyriHaximus** [reactphp/react#382]
As discussed in #380 we're moving  `espresso`, `stomp`, and `partial` to the [Friends of ReactPHP](https://github.com/friends-of-reactphp). We ca do that in several different ways:

* Move the repository, and all it's issues, PR's etc etc over leaving everything intact (Github will arrange the redirect for us so packagist and travis still work). This does keep the package (initially) in the `react` vendor.
* Fork the repository, having to port a all outstanding issues and PR's over, and loosing the history for them on our active repository. But that means we release a new first version under the new vendor and abandon the react package in favour of the Friends of ReactPHP package.

Ping @cboden, @clue, @jsor

**Comment by the-eater** [comment]
Forking has a lot more benefits in this case, we can e.g. also mark `react/stomp` deprecated in favor of `friendlyreaction/stomp` (or what ever the name)

**Comment by jsor** [comment]
@the-eater Looks like you can do this also when moving the repository. The php-cs-fixer repo has been moved over to an organisation:
https://packagist.org/packages/fabpot/php-cs-fixer (abandoned) -> https://packagist.org/packages/friendsofphp/php-cs-fixer.

**Comment by jsor** [comment]
I'm 👍 for moving the repos.

**Comment by the-eater** [comment]
Oh if that's the case, :+1: for moving!

**Comment by kelunik** [comment]
Yes, you can just move it and rename the package in `composer.json` afterwards and resubmit to Packagist.

**Comment by clue** [comment]
> Move the repository, and all it's issues, PR's etc etc over leaving everything intact (Github will arrange the redirect for us so packagist and travis still work). This does keep the package (initially) in the react vendor.

Big plus :+1:

The PRs/issues provide a lot of value (to consumers and maintainers of these packages). If we were to only *copy* things to a new location, we would still have to somehow mark the old location as deprecated, which could cause further friction.

Moving everything to the new location first makes a lot of sense. We could defer the decision if/when renaming the package and vendor namespace makes sense, I have no strong opinion here and would love to hear some more thoughts on this from others :+1:

**Comment by WyriHaximus** [comment]
We've decided to move these repositories to https://github.com/friends-of-reactphp Wednesday evening. I'll move them, and make sure all redirects are working and they can still be installed through composer without issues.

**Comment by WyriHaximus** [comment]
The repositories have been moved :tada:
