### ISSUE TITLE
Keep process running in the background console

### ISSUE THREAD

**Issue by Juanperezc** [reactphp/react#392]
Hello I'm starting with this php react and I really like it a lot, but I have a question about the production version. I have no idea how to execute an asynchronous task which is what I currently have with an infinite loop in a linux server from ssh. how would this and keep that process open all day without closing the ssh console does not close the process in linux.

In addition to this, can I do this at heroku.com?

**Comment by KyleWiering** [comment]
I'd recommend something like systemd in linux. 
Or even something like screen and something to keep the process running if it fails.
It's possible to `detach` from a process as well.

The answer to this question varies by environment. For example: I've used https://github.com/kohsuke/winsw/ quite successfully in windows land.

**Comment by Juanperezc** [comment]
Thank you i think i will use screen :)

**Comment by clue** [comment]
I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
