### ISSUE TITLE
Memory leak Stream.php

### ISSUE THREAD

**Issue by DavidM974** [reactphp/react#393]
Hello, i'm using react lib as a client to connect to a server. And when i run my program non-stop i have a memory exception. Is it possible to clear the stream memory?

Here is my error : Allowed memory size of 1087354687 bytes exhausted (tried to allocate 8182 bytes)  in : Vendor\react\stream\src\Stream.php on line 162.

Any idea to fix this?

**Comment by kelunik** [comment]
The allocation in `Stream.php` was just the one that hit the limit, it doesn't mean it's the place that leaks the memory.

**Comment by DavidM974** [comment]
Yes it's the console Output stream who is more and more bigger i think

**Comment by clue** [comment]
It looks like you're using a somewhat outdated version of [react/stream](https://github.com/reactphp/stream), as the `Stream` class does not exist anymore.

A large number of projects have been using ReactPHP in production for years and we're not aware of any memory leaks with ReactPHP.

Please first update to the latest version. If the problem persists, please open an issue in react/stream and provide some code to reproduce the issue you're seeing and we're happy to look into this. Thanks!
