### ISSUE TITLE
[Improvement] Switch from magic strings to constants

### ISSUE THREAD

**Issue by michaelcullum** [reactphp/react#394]
Currently there are often magic strings used like `data` and `connection`, constants (essentially as enums?) or having a series of different methods should be used instead ideally.

**Comment by WyriHaximus** [comment]
Do like the suggestion and I think constants are the easiest way to implement currently. Using methods would add 3 methods for each type (on, remove, and remove all).

**Comment by clue** [comment]
@michaelcullum Thanks for raising this issue and trying to spark this discussion.

While this has gained little traction, there's an open PR in https://github.com/reactphp/stream/pull/134. The little attention this has received seems to imply there's little interest in pursuing this further, but if this is something you or anybody else is interested in, make sure to contribute to the discussion in the PR :+1:
