### ISSUE TITLE
Why it's named reactphp?

### ISSUE THREAD

**Issue by namnguyen2091** [reactphp/react#425]
**Why it's named reactphp?** I mean react and php, I see it relate to nodejs instead of react.

**Comment by nawarian** [comment]
Quite unfortunate, I know. But React PHP came out before React.JS:

See this first commit: https://github.com/reactphp/react/commit/bbe0956f13356aa7dadb6a1f7a907b06c78f311b

And this first commit: https://github.com/facebook/react/commit/75897c2dcd1dd3a6ca46284dd37e13d22b4b16b4

**Comment by namnguyen2091** [comment]
> Quite unfortunate, I know. But React PHP came out before React.JS:
> 
> See this first commit: [bbe0956](https://github.com/reactphp/react/commit/bbe0956f13356aa7dadb6a1f7a907b06c78f311b)
> 
> And this first commit: [facebook/react@75897c2](https://github.com/facebook/react/commit/75897c2dcd1dd3a6ca46284dd37e13d22b4b16b4)

Sorry, my mistake. I think react is reactjs and mixing reactjs and php is very strange. This is bad idea.

**Comment by WyriHaximus** [comment]
> > Quite unfortunate, I know. But React PHP came out before React.JS:
> > See this first commit: [bbe0956](https://github.com/reactphp/react/commit/bbe0956f13356aa7dadb6a1f7a907b06c78f311b)
> > And this first commit: [facebook/react@75897c2](https://github.com/facebook/react/commit/75897c2dcd1dd3a6ca46284dd37e13d22b4b16b4)
> 
> Sorry, my mistake. I think react is reactjs and mixing reactjs and php is very strange. This is my bad idea.

And that's why we're always referring to it as ReactPHP and not just react :D

**Comment by kelunik** [comment]
> See this first commit: [bbe0956](https://github.com/reactphp/react/commit/bbe0956f13356aa7dadb6a1f7a907b06c78f311b)

At that point it wasn't named ReactPHP, yet. :stuck_out_tongue_winking_eye:

**Comment by WyriHaximus** [comment]
> > See this first commit: [bbe0956](https://github.com/reactphp/react/commit/bbe0956f13356aa7dadb6a1f7a907b06c78f311b)
> 
> At that point it wasn't named ReactPHP, yet.

That happened two weeks later https://github.com/reactphp/react/commit/e36fb2623b0eb1018ce622bc0ba374a85be1788a :stuck_out_tongue_winking_eye:

**Comment by odahcam** [comment]
I hope no one steals Revolts name.

**Comment by henrik-nordstrom** [comment]
> I hope no one steals Revolts name.

That would be quite revolting
