### ISSUE TITLE
Libuv

### ISSUE THREAD

**Issue by igorw** [reactphp/react#55]
Provides eventloop, buffer, dns, (socket?) and http implementations.
- https://github.com/chobie/php-uv

**Comment by Andrewpk** [comment]
I know this is two years old, but I'm just here to +1 this issue. If added, we'd have native async in hhvm via https://github.com/RickySu/hhvm-ext-uv or https://github.com/chobie/hhvm-uv depending on loop support.

**Comment by cboden** [comment]
@Andrewpk not to worry, it's [in progress](https://github.com/reactphp/event-loop/pull/17)!  :)

**Comment by Andrewpk** [comment]
@cboden ![AWWW YISSS](http://www.reactiongifs.com/wp-content/gallery/yes/tumblr_lm11bt4OaK1qe6xr2.gif "AWWW YISSS")


Thanks for the update!

**Comment by clue** [comment]
See https://github.com/reactphp/event-loop/pull/17
