### ISSUE TITLE
[HttpParser] New component

### ISSUE THREAD

**Issue by igorw** [reactphp/react#6]
Port the [mongrel http parser](https://github.com/zedshaw/mongrel2/tree/master/src/http11) to PHP. Or maybe the [node](https://github.com/joyent/http-parser/blob/master/http_parser.c) one.

Also provide adapters for PHP extensions:
- [httpparser-php](https://github.com/dhotson/httpparser-php) (mongrel)
- [php-httpparser](https://github.com/crodas/PHP-HttpParser) (node)

**Comment by clue** [comment]
Also consider checking out #233.

**Comment by clue** [comment]
See https://github.com/reactphp/http/issues/14 and https://github.com/reactphp/http/issues/19
