### ISSUE TITLE
popen() streams sometimes block the event loop

### ISSUE THREAD

**Issue by schmod** [reactphp/react#68]
I'm writing a small application using React and Ratchet that opens up a few long-running external processes, and redirects some of their output (via stdout) through a websocket connection.  

Using `popen` and React's `stream` class to talk to the external process usually works just fine, and the process's output gets sent to the websocket as it executes -- as one would expect.  Some processes, however, block the event loop until they've completed running.  

Inside my Ratchet application, I can run 
```php
$ping = new Stream(popen("ping -t 127.0.0.1",'r'),$server->loop);
$ping->on('data',function($data) use ($from){
    $from->send($data);
});
```
and ping will continuously direct its output through my websocket connection, `$from`.

However, if I use a different executable (in this case, the [Adobe F4V Post-Processor](http://www.adobe.com/products/flash-media-server-family/tool-downloads.html)), I get no output from f4vpp, or anything else in my event loop (say, the `ping` command above) until f4vpp exits.
```php
$f4vpp = new Stream(popen("f4vpp -v -i in.f4v -o out.mp4",'r'),$server->loop);
$f4vpp->on('data',function($data) use ($from){
    $from->send($data);
});
```

What's going on here?  Is this user error, or a legitimate shortcoming in React or PHP on win32?

**Comment by clue** [comment]
> What's going on here? Is this user error, or a legitimate shortcoming in React or PHP on win32?

Looks like this is a limitation of Windows and there's little PHP can do about this, see also https://github.com/reactphp/child-process/issues/9.

This hasn't received any input in a while, so I'll close this for now. Please come back with more details if this problem persists and we can reopen this :+1:
